# Generated by Django 5.2.11 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAssistants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('tazkira_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('emergency_phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_assistants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('tazkira_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('emergency_phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
    ]
