# Generated by Django 5.2.11 on 2026-04-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='PermissionGroups',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='RolePermissions',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
