# Generated by Django 5.2.11 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripPassengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_passengers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('assigned_by', models.IntegerField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('trip_status', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_status', models.TextField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_status_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('assigned_by', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_assignments',
                'managed': False,
            },
        ),
    ]
