# Generated by Django 5.2.11 on 2026-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField(blank=True, null=True)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('reported_by', models.IntegerField(blank=True, null=True)),
                ('incident_time', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
    ]
